default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  database: <%= Rails.application.credentials.dig(:database, :database) %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>

development:
  <<: *default

test:
  <<: *default
  database: microservices_db_test

production:
  <<: *default
  database: microservices_db_production
